### ISSUE TITLE
Voter VoterState Change event

### ISSUE THREAD

**Issue by rudy2steiner** [chubaostream/journalkeeper#19]
VoterState{LEADER, FOLLOWER, CANDIDATE, PRE_VOTING} 决定节点是否有可读写(writable/readable). 目前, 可以通过Voter#getServerStatus主动获取节点的选举, 有些场景需要监听VoterState的变化，并做出响应

**Comment by liyue2008** [comment]
实现某个节点状态变化的事件，对于JournalKeeper目前的事件模型来说有挑战。

原因是，JournalKeeper事件都是基于集群的变化而产生。因为集群的变化通过日志会复制到集群的每个节点上，所以可以保证集群的每个节点都可以感知到集群的全部变化，从而发送事件。

订阅事件的客户端从集群的任意一个节点上订阅，都可以收到集群内的全部事件。但某个节点状态变化，并不属于“集群状态变化”，没有写入日志，集群的其它节点感知不到这个变化，这样连接到其它节点的客户端都无法收到这个事件。

可能的一个解决思路是，将节点状态变化写入日志，但节点状态变化时，很可能集群是不可用的，写日志失败的概率很大。

另一个思路是，让客户端连接集群所有的节点，但这并不是一个优雅的解决问题方式。

**Comment by rudy2steiner** [comment]
https://github.com/chubaostream/joyqueue/blob/dev/joyqueue-server/joyqueue-broker-core/src/main/java/org/joyqueue/broker/store/ClusterStoreService.java 

中利用了选举服务的当前leader, 节点构造了 存储节点的状态（标识节点是否可写），如果journalKeeper 要作为joyqueue 的存储，也需要实现类似的功能

**Comment by liyue2008** [comment]
只有leader节点是可写的，其他节点都是只读的，所以只需要监听ON_LEADER_CHANGE事件即可。
